POST http://localhost:8080/create-developers
Content-Type: application/json

{
 "developerLevel":"JUNIOR",
  "developerSkillType":"BACKEND",
  "name":"kihoon",
  "experienceYears": -2,
  "memberId":22,
  "age":20
}
###
