POST http://localhost:8080/create-developers
Content-Type: application/json

{
 "developerLevel":"JUNGNIOR",
  "developerSkillType":"BACKEND",
  "name":"kihon",
  "experienceYears": 10,
  "memberId":3,
  "age":20
}

